build_image:
  image: docker:git
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/wutiarn/flibusta-bot .
    - docker push registry.gitlab.com/wutiarn/flibusta-bot:latest
  only:
    - master

deploy:
  stage: deploy
  script:
    - curl -X POST -F token=$EDUSTOR_DEPLOY_TRIGGER_TOKEN -F ref=master https://gitlab.com/api/v3/projects/1237981/trigger/build