build_image:
  image: docker:git
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/wutiarn/flibusta-bot .
    - docker push registry.gitlab.com/wutiarn/flibusta-bot:latest
  only:
    - master

deploy:
  image: wutiarn/rancher-deployer
  stage: deploy
  script:
    - /root/upgrade.sh