version: "2"

services:
  flibusta:
    image: registry.gitlab.com/wutiarn/flibusta-bot
    volumes:
      - /path/to/flibusta/archive:/code/data
    environment:
      TELEGRAM_TOKEN: telegram_token
    restart: unless-stopped